### ISSUE TITLE
Development Environment with Docker Compose?

### ISSUE THREAD

**Issue by simenandre** [gathering/wannabe#6]
Hello 👋

I'd like to suggest that we add a `docker-compose.yml` file. This way it's easy for anyone to boot the project – and well, quicker. 

Can also be used for integration testing. I can probably create a pull request on it.

**Comment by KristianLyng** [comment]
I was thinking along the same lines. Care to do the honors?

**Comment by simenandre** [comment]
Yeah – might not be until mid next week tho'. 👍

**Comment by Atriusftw** [comment]
I recommend using PHP7 in the composefile :)

**Comment by simenandre** [comment]
PHP7 with latest version then?

**Comment by Koch** [comment]
I'll start working on this too, asap :)

**Comment by simenandre** [comment]
@Koch Oh, if you do this, I'll leave it then?

**Comment by Koch** [comment]
I can do this, yeah!

**Comment by KristianLyng** [comment]
So I threw together something really basic because I'm impatient. This still doesn't really work, but not because of docker.

The Dockerfile in the repo will set up most things you really need, but since our code-base isn't really compatible with php7.3, we need to make some updates. I've started on these, but it'll take a little while since I need to ensure the old version keeps working until we can switch production.

I'm keeping this issue open because until the dev environment is actually DECENT, there's tons of work to do.

**Comment by KristianLyng** [comment]
ffs, how can github NOT support files with ".patch" ........ what stupid fucked up shit is this.

Anyway, this is what I did to get the front page to work. Some of this is pretty straight forward and non-controversial (e.g.: Actually defining variables before using them), but I need to verify some of it (e.g.: the ini-lol, and locale obviously). But it should give people an idea of what's needed.

[php7.3.patch.txt](https://github.com/gathering/wannabe/files/3525480/php7.3.patch.txt)

**Comment by Koch** [comment]
Going to be looking at this this weekend when I have a bit more time to use, and will hopefully have a PR coming up that we can work in.

**Comment by Atriusftw** [comment]
Closing this as we now have a working docker-compose setup from #30 🎉
